version: "3.2"

services:
  BTCUSDT:
    image: btcusdt-service
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "python3 BTCUSDT/collector.py"
    volumes:
      - ../BTCUSDT/:/usr/src/pipelines/BTCUSDT/
    networks:
      - coin

  ETHUSDT:
    image: ethusdt-service
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python3 ETHUSDT/collector.py
    volumes:
      - ../ETHUSDT/:/usr/src/pipelines/ETHUSDT/
    networks:
      - coin

  DOGEUSDT:
    image: dogeusdt-service
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python3 DOGEUSDT/collector.py
    volumes:
      - ../DOGEUSDT/:/usr/src/pipelines/DOGEUSDT/
    networks:
      - coin

volumes:
  pipelines_coin:
    external: true

networks:
  coin:
    external: true
