version: "3.2"

services:
  DOGEUSDT:
    image: dogeusdt-service
    build:
      context: .
      dockerfile: ../Dockerfile
    command: python3 DOGEUSDT/collector.py
    volumes:
      - ../DOGEUSDT/:/usr/src/pipelines/DOGEUSDT/
    networks:
      - coin

volumes:
  pipelines_coin:
    external: true

networks:
  coin:
    external: true
